// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const browseUserCards = `-- name: BrowseUserCards :many
SELECT c.id, c.deck_id, c.front, c.back, c.audio_url, c.imagem_url, c.fonetica, c.tts_enabled, c.stability, c.difficulty, c.due, c.last_review, c.state, c.reps, c.lapses, c.fsrs_card_json, c.row_version, c.created_at, c.updated_at
FROM cards c
JOIN decks d ON d.id = c.deck_id
WHERE d.user_id = $1
  AND ($2::text IS NULL OR c.state = $2)
  AND ($3::uuid IS NULL OR c.deck_id = $3)
  AND ($4::timestamptz IS NULL OR c.due <= $4)
  AND ($5::timestamptz IS NULL OR c.created_at >= $5)
  AND (
    $6::timestamptz IS NULL
    OR (c.updated_at >= $6 AND c.created_at < $6)
  )
  AND (
    $7::boolean IS NULL
    OR $7 = FALSE
    OR (d.tags IS NULL OR cardinality(d.tags) = 0)
  )
ORDER BY c.created_at DESC
`

type BrowseUserCardsParams struct {
	UserID       uuid.UUID  `json:"user_id"`
	State        *string    `json:"state"`
	DeckID       *uuid.UUID `json:"deck_id"`
	DueBefore    *time.Time `json:"due_before"`
	CreatedAfter *time.Time `json:"created_after"`
	EditedAfter  *time.Time `json:"edited_after"`
	UntaggedOnly *bool      `json:"untagged_only"`
}

func (q *Queries) BrowseUserCards(ctx context.Context, arg BrowseUserCardsParams) ([]Card, error) {
	rows, err := q.db.Query(ctx, browseUserCards,
		arg.UserID,
		arg.State,
		arg.DeckID,
		arg.DueBefore,
		arg.CreatedAfter,
		arg.EditedAfter,
		arg.UntaggedOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.AudioUrl,
			&i.ImagemUrl,
			&i.Fonetica,
			&i.TtsEnabled,
			&i.Stability,
			&i.Difficulty,
			&i.Due,
			&i.LastReview,
			&i.State,
			&i.Reps,
			&i.Lapses,
			&i.FsrsCardJson,
			&i.RowVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCardsByDeck = `-- name: CountCardsByDeck :one
SELECT COUNT(*) FROM cards WHERE deck_id = $1
`

func (q *Queries) CountCardsByDeck(ctx context.Context, deckID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCardsByDeck, deckID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDueCardsByDeck = `-- name: CountDueCardsByDeck :one
WITH ranked AS (
    SELECT state,
        CASE
            WHEN state = 'new' THEN ROW_NUMBER() OVER (PARTITION BY (state = 'new') ORDER BY due ASC)
            ELSE 0
        END AS new_rank
    FROM cards
    WHERE deck_id = $1 AND due <= $2
)
SELECT COUNT(*)::bigint FROM ranked
WHERE state != 'new' OR new_rank <= $3::bigint
`

type CountDueCardsByDeckParams struct {
	DeckID      uuid.UUID `json:"deck_id"`
	Due         time.Time `json:"due"`
	MaxNewCards int64     `json:"max_new_cards"`
}

// Mirrors the new-card cap applied in ListDueCardsByDeck so TotalDue
// matches what pagination can actually return.
func (q *Queries) CountDueCardsByDeck(ctx context.Context, arg CountDueCardsByDeckParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDueCardsByDeck, arg.DeckID, arg.Due, arg.MaxNewCards)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countNewCardsStudiedToday = `-- name: CountNewCardsStudiedToday :one
SELECT COUNT(DISTINCT r.card_id) FROM reviews r
JOIN cards c ON c.id = r.card_id
WHERE c.deck_id = $1
  AND r.user_id = $2
  AND r.review_datetime >= $3
  AND r.elapsed_days = 0
`

type CountNewCardsStudiedTodayParams struct {
	DeckID         uuid.UUID `json:"deck_id"`
	UserID         uuid.UUID `json:"user_id"`
	ReviewDatetime time.Time `json:"review_datetime"`
}

func (q *Queries) CountNewCardsStudiedToday(ctx context.Context, arg CountNewCardsStudiedTodayParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNewCardsStudiedToday, arg.DeckID, arg.UserID, arg.ReviewDatetime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserCards = `-- name: CountUserCards :one
SELECT COUNT(*)::bigint
FROM cards c
JOIN decks d ON d.id = c.deck_id
WHERE d.user_id = $1
`

func (q *Queries) CountUserCards(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserCards, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUserCardsByState = `-- name: CountUserCardsByState :many
SELECT c.state, COUNT(*)::bigint AS count
FROM cards c
JOIN decks d ON d.id = c.deck_id
WHERE d.user_id = $1
GROUP BY c.state
`

type CountUserCardsByStateRow struct {
	State string `json:"state"`
	Count int64  `json:"count"`
}

func (q *Queries) CountUserCardsByState(ctx context.Context, userID uuid.UUID) ([]CountUserCardsByStateRow, error) {
	rows, err := q.db.Query(ctx, countUserCardsByState, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountUserCardsByStateRow
	for rows.Next() {
		var i CountUserCardsByStateRow
		if err := rows.Scan(&i.State, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUserCardsCreatedSince = `-- name: CountUserCardsCreatedSince :one
SELECT COUNT(*)::bigint
FROM cards c
JOIN decks d ON d.id = c.deck_id
WHERE d.user_id = $1
  AND c.created_at >= $2
`

type CountUserCardsCreatedSinceParams struct {
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CountUserCardsCreatedSince(ctx context.Context, arg CountUserCardsCreatedSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserCardsCreatedSince, arg.UserID, arg.CreatedAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUserCardsDueBy = `-- name: CountUserCardsDueBy :one
SELECT COUNT(*)::bigint
FROM cards c
JOIN decks d ON d.id = c.deck_id
WHERE d.user_id = $1
  AND c.due <= $2
`

type CountUserCardsDueByParams struct {
	UserID uuid.UUID `json:"user_id"`
	Due    time.Time `json:"due"`
}

func (q *Queries) CountUserCardsDueBy(ctx context.Context, arg CountUserCardsDueByParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserCardsDueBy, arg.UserID, arg.Due)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUserCardsEditedSince = `-- name: CountUserCardsEditedSince :one
SELECT COUNT(*)::bigint
FROM cards c
JOIN decks d ON d.id = c.deck_id
WHERE d.user_id = $1
  AND c.updated_at >= $2
  AND c.created_at < $2
`

type CountUserCardsEditedSinceParams struct {
	UserID    uuid.UUID `json:"user_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CountUserCardsEditedSince(ctx context.Context, arg CountUserCardsEditedSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserCardsEditedSince, arg.UserID, arg.UpdatedAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUserCardsInUntaggedDecks = `-- name: CountUserCardsInUntaggedDecks :one
SELECT COUNT(*)::bigint
FROM cards c
JOIN decks d ON d.id = c.deck_id
WHERE d.user_id = $1
  AND (d.tags IS NULL OR cardinality(d.tags) = 0)
`

func (q *Queries) CountUserCardsInUntaggedDecks(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserCardsInUntaggedDecks, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createCard = `-- name: CreateCard :one
INSERT INTO cards (
    deck_id, front, back, audio_url, imagem_url, fonetica,
    tts_enabled, state, stability, difficulty, due, fsrs_card_json
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, deck_id, front, back, audio_url, imagem_url, fonetica, tts_enabled, stability, difficulty, due, last_review, state, reps, lapses, fsrs_card_json, row_version, created_at, updated_at
`

type CreateCardParams struct {
	DeckID       uuid.UUID `json:"deck_id"`
	Front        string    `json:"front"`
	Back         string    `json:"back"`
	AudioUrl     *string   `json:"audio_url"`
	ImagemUrl    *string   `json:"imagem_url"`
	Fonetica     *string   `json:"fonetica"`
	TtsEnabled   bool      `json:"tts_enabled"`
	State        string    `json:"state"`
	Stability    float64   `json:"stability"`
	Difficulty   float64   `json:"difficulty"`
	Due          time.Time `json:"due"`
	FsrsCardJson *string   `json:"fsrs_card_json"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.DeckID,
		arg.Front,
		arg.Back,
		arg.AudioUrl,
		arg.ImagemUrl,
		arg.Fonetica,
		arg.TtsEnabled,
		arg.State,
		arg.Stability,
		arg.Difficulty,
		arg.Due,
		arg.FsrsCardJson,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.Front,
		&i.Back,
		&i.AudioUrl,
		&i.ImagemUrl,
		&i.Fonetica,
		&i.TtsEnabled,
		&i.Stability,
		&i.Difficulty,
		&i.Due,
		&i.LastReview,
		&i.State,
		&i.Reps,
		&i.Lapses,
		&i.FsrsCardJson,
		&i.RowVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (
    card_id, user_id, rating, state, scheduled_days, elapsed_days,
    review_datetime, review_duration_ms, stability, difficulty
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, card_id, user_id, rating, state, scheduled_days, elapsed_days, review_datetime, review_duration_ms, stability, difficulty
`

type CreateReviewParams struct {
	CardID           uuid.UUID `json:"card_id"`
	UserID           uuid.UUID `json:"user_id"`
	Rating           int32     `json:"rating"`
	State            string    `json:"state"`
	ScheduledDays    int32     `json:"scheduled_days"`
	ElapsedDays      int32     `json:"elapsed_days"`
	ReviewDatetime   time.Time `json:"review_datetime"`
	ReviewDurationMs *int32    `json:"review_duration_ms"`
	Stability        float64   `json:"stability"`
	Difficulty       float64   `json:"difficulty"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.CardID,
		arg.UserID,
		arg.Rating,
		arg.State,
		arg.ScheduledDays,
		arg.ElapsedDays,
		arg.ReviewDatetime,
		arg.ReviewDurationMs,
		arg.Stability,
		arg.Difficulty,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.UserID,
		&i.Rating,
		&i.State,
		&i.ScheduledDays,
		&i.ElapsedDays,
		&i.ReviewDatetime,
		&i.ReviewDurationMs,
		&i.Stability,
		&i.Difficulty,
	)
	return i, err
}

const deckStatsByUser = `-- name: DeckStatsByUser :many
SELECT
    d.id AS deck_id,
    d.new_cards_daily_limit,
    COALESCE(SUM(CASE WHEN c.state = 'new' THEN 1 ELSE 0 END), 0)::bigint AS new_count,
    COALESCE(SUM(CASE WHEN (c.state = 'learning' OR c.state = 'relearning') AND c.due <= $2 THEN 1 ELSE 0 END), 0)::bigint AS learning_count,
    COALESCE(SUM(CASE WHEN c.state = 'review' AND c.due <= $2 THEN 1 ELSE 0 END), 0)::bigint AS review_count,
    COALESCE(COUNT(c.id), 0)::bigint AS total_cards,
    COALESCE(st.studied_today, 0)::bigint AS new_cards_studied_today
FROM decks d
LEFT JOIN cards c ON c.deck_id = d.id
LEFT JOIN (
    SELECT c2.deck_id, COUNT(DISTINCT r.card_id) AS studied_today
    FROM reviews r
    JOIN cards c2 ON c2.id = r.card_id
    WHERE r.user_id = $1
      AND r.review_datetime >= $3
      AND r.elapsed_days = 0
    GROUP BY c2.deck_id
) st ON st.deck_id = d.id
WHERE d.user_id = $1
GROUP BY d.id, d.new_cards_daily_limit, st.studied_today
ORDER BY d.created_at DESC
`

type DeckStatsByUserParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Due        time.Time `json:"due"`
	StartOfDay time.Time `json:"start_of_day"`
}

type DeckStatsByUserRow struct {
	DeckID               uuid.UUID `json:"deck_id"`
	NewCardsDailyLimit   int32     `json:"new_cards_daily_limit"`
	NewCount             int64     `json:"new_count"`
	LearningCount        int64     `json:"learning_count"`
	ReviewCount          int64     `json:"review_count"`
	TotalCards           int64     `json:"total_cards"`
	NewCardsStudiedToday int64     `json:"new_cards_studied_today"`
}

func (q *Queries) DeckStatsByUser(ctx context.Context, arg DeckStatsByUserParams) ([]DeckStatsByUserRow, error) {
	rows, err := q.db.Query(ctx, deckStatsByUser, arg.UserID, arg.Due, arg.StartOfDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeckStatsByUserRow
	for rows.Next() {
		var i DeckStatsByUserRow
		if err := rows.Scan(
			&i.DeckID,
			&i.NewCardsDailyLimit,
			&i.NewCount,
			&i.LearningCount,
			&i.ReviewCount,
			&i.TotalCards,
			&i.NewCardsStudiedToday,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM cards WHERE id = $1
`

func (q *Queries) DeleteCard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCard, id)
	return err
}

const getCardByID = `-- name: GetCardByID :one
SELECT id, deck_id, front, back, audio_url, imagem_url, fonetica, tts_enabled, stability, difficulty, due, last_review, state, reps, lapses, fsrs_card_json, row_version, created_at, updated_at FROM cards WHERE id = $1
`

func (q *Queries) GetCardByID(ctx context.Context, id uuid.UUID) (Card, error) {
	row := q.db.QueryRow(ctx, getCardByID, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.Front,
		&i.Back,
		&i.AudioUrl,
		&i.ImagemUrl,
		&i.Fonetica,
		&i.TtsEnabled,
		&i.Stability,
		&i.Difficulty,
		&i.Due,
		&i.LastReview,
		&i.State,
		&i.Reps,
		&i.Lapses,
		&i.FsrsCardJson,
		&i.RowVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCardsByDeck = `-- name: ListCardsByDeck :many
SELECT id, deck_id, front, back, audio_url, imagem_url, fonetica, tts_enabled, stability, difficulty, due, last_review, state, reps, lapses, fsrs_card_json, row_version, created_at, updated_at FROM cards WHERE deck_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListCardsByDeck(ctx context.Context, deckID uuid.UUID) ([]Card, error) {
	rows, err := q.db.Query(ctx, listCardsByDeck, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.AudioUrl,
			&i.ImagemUrl,
			&i.Fonetica,
			&i.TtsEnabled,
			&i.Stability,
			&i.Difficulty,
			&i.Due,
			&i.LastReview,
			&i.State,
			&i.Reps,
			&i.Lapses,
			&i.FsrsCardJson,
			&i.RowVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueCardsByDeck = `-- name: ListDueCardsByDeck :many
WITH ranked AS (
    SELECT id, deck_id, front, back, audio_url, imagem_url, fonetica, tts_enabled, stability, difficulty, due, last_review, state, reps, lapses, fsrs_card_json, row_version, created_at, updated_at,
        CASE
            WHEN state = 'new' THEN ROW_NUMBER() OVER (PARTITION BY (state = 'new') ORDER BY due ASC)
            ELSE 0
        END AS new_rank
    FROM cards
    WHERE deck_id = $1 AND due <= $2
)
SELECT id, deck_id, front, back, audio_url, imagem_url, fonetica, tts_enabled, stability, difficulty, due, last_review, state, reps, lapses, fsrs_card_json, row_version, created_at, updated_at
FROM ranked
WHERE state != 'new' OR new_rank <= $5::bigint
ORDER BY due ASC
LIMIT $3 OFFSET $4
`

type ListDueCardsByDeckParams struct {
	DeckID      uuid.UUID `json:"deck_id"`
	Due         time.Time `json:"due"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
	MaxNewCards int64     `json:"max_new_cards"`
}

type ListDueCardsByDeckRow struct {
	ID           uuid.UUID  `json:"id"`
	DeckID       uuid.UUID  `json:"deck_id"`
	Front        string     `json:"front"`
	Back         string     `json:"back"`
	AudioUrl     *string    `json:"audio_url"`
	ImagemUrl    *string    `json:"imagem_url"`
	Fonetica     *string    `json:"fonetica"`
	TtsEnabled   bool       `json:"tts_enabled"`
	Stability    float64    `json:"stability"`
	Difficulty   float64    `json:"difficulty"`
	Due          time.Time  `json:"due"`
	LastReview   *time.Time `json:"last_review"`
	State        string     `json:"state"`
	Reps         int32      `json:"reps"`
	Lapses       int32      `json:"lapses"`
	FsrsCardJson *string    `json:"fsrs_card_json"`
	RowVersion   int32      `json:"row_version"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

// Ranks 'new' cards by due date and drops any beyond sqlc.arg(max_new_cards)
// BEFORE applying LIMIT/OFFSET, so pagination reflects exactly what the
// caller is allowed to consume (see CountDueCardsByDeck for the matching
// total). Non-new cards are never capped by this rank.
func (q *Queries) ListDueCardsByDeck(ctx context.Context, arg ListDueCardsByDeckParams) ([]ListDueCardsByDeckRow, error) {
	rows, err := q.db.Query(ctx, listDueCardsByDeck,
		arg.DeckID,
		arg.Due,
		arg.Limit,
		arg.Offset,
		arg.MaxNewCards,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueCardsByDeckRow
	for rows.Next() {
		var i ListDueCardsByDeckRow
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.AudioUrl,
			&i.ImagemUrl,
			&i.Fonetica,
			&i.TtsEnabled,
			&i.Stability,
			&i.Difficulty,
			&i.Due,
			&i.LastReview,
			&i.State,
			&i.Reps,
			&i.Lapses,
			&i.FsrsCardJson,
			&i.RowVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueCardsByUser = `-- name: ListDueCardsByUser :many
SELECT c.id, c.deck_id, c.front, c.back, c.audio_url, c.imagem_url, c.fonetica, c.tts_enabled, c.stability, c.difficulty, c.due, c.last_review, c.state, c.reps, c.lapses, c.fsrs_card_json, c.row_version, c.created_at, c.updated_at FROM cards c
JOIN decks d ON d.id = c.deck_id
WHERE d.user_id = $1 AND c.due <= $2
ORDER BY c.due ASC
LIMIT $3 OFFSET $4
`

type ListDueCardsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Due    time.Time `json:"due"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListDueCardsByUser(ctx context.Context, arg ListDueCardsByUserParams) ([]Card, error) {
	rows, err := q.db.Query(ctx, listDueCardsByUser,
		arg.UserID,
		arg.Due,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.AudioUrl,
			&i.ImagemUrl,
			&i.Fonetica,
			&i.TtsEnabled,
			&i.Stability,
			&i.Difficulty,
			&i.Due,
			&i.LastReview,
			&i.State,
			&i.Reps,
			&i.Lapses,
			&i.FsrsCardJson,
			&i.RowVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByUserForOptimizer = `-- name: ListReviewsByUserForOptimizer :many
SELECT card_id, rating, review_datetime
FROM reviews
WHERE user_id = $1
ORDER BY card_id, review_datetime ASC
`

type ListReviewsByUserForOptimizerRow struct {
	CardID         uuid.UUID `json:"card_id"`
	Rating         int32     `json:"rating"`
	ReviewDatetime time.Time `json:"review_datetime"`
}

func (q *Queries) ListReviewsByUserForOptimizer(ctx context.Context, userID uuid.UUID) ([]ListReviewsByUserForOptimizerRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByUserForOptimizer, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsByUserForOptimizerRow
	for rows.Next() {
		var i ListReviewsByUserForOptimizerRow
		if err := rows.Scan(&i.CardID, &i.Rating, &i.ReviewDatetime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveCard = `-- name: MoveCard :one
UPDATE cards
SET deck_id = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, deck_id, front, back, audio_url, imagem_url, fonetica, tts_enabled, stability, difficulty, due, last_review, state, reps, lapses, fsrs_card_json, row_version, created_at, updated_at
`

type MoveCardParams struct {
	ID     uuid.UUID `json:"id"`
	DeckID uuid.UUID `json:"deck_id"`
}

func (q *Queries) MoveCard(ctx context.Context, arg MoveCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, moveCard, arg.ID, arg.DeckID)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.Front,
		&i.Back,
		&i.AudioUrl,
		&i.ImagemUrl,
		&i.Fonetica,
		&i.TtsEnabled,
		&i.Stability,
		&i.Difficulty,
		&i.Due,
		&i.LastReview,
		&i.State,
		&i.Reps,
		&i.Lapses,
		&i.FsrsCardJson,
		&i.RowVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCard = `-- name: UpdateCard :one
UPDATE cards
SET front = COALESCE($2, front),
    back = COALESCE($3, back),
    audio_url = COALESCE($4, audio_url),
    imagem_url = COALESCE($5, imagem_url),
    fonetica = COALESCE($6, fonetica),
    tts_enabled = COALESCE($7, tts_enabled),
    updated_at = NOW()
WHERE id = $1
RETURNING id, deck_id, front, back, audio_url, imagem_url, fonetica, tts_enabled, stability, difficulty, due, last_review, state, reps, lapses, fsrs_card_json, row_version, created_at, updated_at
`

type UpdateCardParams struct {
	ID         uuid.UUID `json:"id"`
	Front      *string   `json:"front"`
	Back       *string   `json:"back"`
	AudioUrl   *string   `json:"audio_url"`
	ImagemUrl  *string   `json:"imagem_url"`
	Fonetica   *string   `json:"fonetica"`
	TtsEnabled *bool     `json:"tts_enabled"`
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, updateCard,
		arg.ID,
		arg.Front,
		arg.Back,
		arg.AudioUrl,
		arg.ImagemUrl,
		arg.Fonetica,
		arg.TtsEnabled,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.Front,
		&i.Back,
		&i.AudioUrl,
		&i.ImagemUrl,
		&i.Fonetica,
		&i.TtsEnabled,
		&i.Stability,
		&i.Difficulty,
		&i.Due,
		&i.LastReview,
		&i.State,
		&i.Reps,
		&i.Lapses,
		&i.FsrsCardJson,
		&i.RowVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCardAfterReview = `-- name: UpdateCardAfterReview :one
UPDATE cards
SET state = $2,
    stability = $3,
    difficulty = $4,
    due = $5,
    last_review = $6,
    reps = $7,
    lapses = $8,
    fsrs_card_json = $9,
    row_version = row_version + 1,
    updated_at = NOW()
WHERE id = $1 AND row_version = $10
RETURNING id, deck_id, front, back, audio_url, imagem_url, fonetica, tts_enabled, stability, difficulty, due, last_review, state, reps, lapses, fsrs_card_json, row_version, created_at, updated_at
`

type UpdateCardAfterReviewParams struct {
	ID           uuid.UUID  `json:"id"`
	State        string     `json:"state"`
	Stability    float64    `json:"stability"`
	Difficulty   float64    `json:"difficulty"`
	Due          time.Time  `json:"due"`
	LastReview   *time.Time `json:"last_review"`
	Reps         int32      `json:"reps"`
	Lapses       int32      `json:"lapses"`
	FsrsCardJson *string    `json:"fsrs_card_json"`
	RowVersion   int32      `json:"row_version"`
}

func (q *Queries) UpdateCardAfterReview(ctx context.Context, arg UpdateCardAfterReviewParams) (Card, error) {
	row := q.db.QueryRow(ctx, updateCardAfterReview,
		arg.ID,
		arg.State,
		arg.Stability,
		arg.Difficulty,
		arg.Due,
		arg.LastReview,
		arg.Reps,
		arg.Lapses,
		arg.FsrsCardJson,
		arg.RowVersion,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.Front,
		&i.Back,
		&i.AudioUrl,
		&i.ImagemUrl,
		&i.Fonetica,
		&i.TtsEnabled,
		&i.Stability,
		&i.Difficulty,
		&i.Due,
		&i.LastReview,
		&i.State,
		&i.Reps,
		&i.Lapses,
		&i.FsrsCardJson,
		&i.RowVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
