// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decks.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createDeck = `-- name: CreateDeck :one

INSERT INTO decks (user_id, name, description, tags, new_cards_daily_limit, module_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, description, tags, new_cards_daily_limit, created_at, updated_at, module_id
`

type CreateDeckParams struct {
	UserID             uuid.UUID  `json:"user_id"`
	Name               string     `json:"name"`
	Description        *string    `json:"description"`
	Tags               []string   `json:"tags"`
	NewCardsDailyLimit int32      `json:"new_cards_daily_limit"`
	ModuleID           *uuid.UUID `json:"module_id"`
}

// apps/api/queries/decks.sql
func (q *Queries) CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error) {
	row := q.db.QueryRow(ctx, createDeck,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Tags,
		arg.NewCardsDailyLimit,
		arg.ModuleID,
	)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Tags,
		&i.NewCardsDailyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModuleID,
	)
	return i, err
}

const deleteDeck = `-- name: DeleteDeck :exec
DELETE FROM decks WHERE id = $1 AND user_id = $2
`

type DeleteDeckParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteDeck(ctx context.Context, arg DeleteDeckParams) error {
	_, err := q.db.Exec(ctx, deleteDeck, arg.ID, arg.UserID)
	return err
}

const getDeckByID = `-- name: GetDeckByID :one
SELECT id, user_id, name, description, tags, new_cards_daily_limit, created_at, updated_at, module_id FROM decks WHERE id = $1
`

func (q *Queries) GetDeckByID(ctx context.Context, id uuid.UUID) (Deck, error) {
	row := q.db.QueryRow(ctx, getDeckByID, id)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Tags,
		&i.NewCardsDailyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModuleID,
	)
	return i, err
}

const getDeckByIDForUpdate = `-- name: GetDeckByIDForUpdate :one
SELECT id, user_id, name, description, tags, new_cards_daily_limit, created_at, updated_at, module_id FROM decks WHERE id = $1 FOR UPDATE
`

// Locks the deck row so a concurrent review submission can't read the same
// new-cards-studied-today count before this transaction commits its update.
func (q *Queries) GetDeckByIDForUpdate(ctx context.Context, id uuid.UUID) (Deck, error) {
	row := q.db.QueryRow(ctx, getDeckByIDForUpdate, id)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Tags,
		&i.NewCardsDailyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModuleID,
	)
	return i, err
}

const listDecksByUser = `-- name: ListDecksByUser :many
SELECT id, user_id, name, description, tags, new_cards_daily_limit, created_at, updated_at, module_id FROM decks WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDecksByUser(ctx context.Context, userID uuid.UUID) ([]Deck, error) {
	rows, err := q.db.Query(ctx, listDecksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deck
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Tags,
			&i.NewCardsDailyLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModuleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeck = `-- name: UpdateDeck :one
UPDATE decks
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    tags = COALESCE($4, tags),
    new_cards_daily_limit = COALESCE($5, new_cards_daily_limit),
    module_id = CASE
        WHEN $6::boolean THEN $7
        ELSE module_id
    END,
    updated_at = NOW()
WHERE id = $1 AND user_id = $8
RETURNING id, user_id, name, description, tags, new_cards_daily_limit, created_at, updated_at, module_id
`

type UpdateDeckParams struct {
	ID                 uuid.UUID  `json:"id"`
	Name               *string    `json:"name"`
	Description        *string    `json:"description"`
	Tags               []string   `json:"tags"`
	NewCardsDailyLimit *int32     `json:"new_cards_daily_limit"`
	ModuleIDSet        *bool      `json:"module_id_set"`
	ModuleID           *uuid.UUID `json:"module_id"`
	UserID             uuid.UUID  `json:"user_id"`
}

func (q *Queries) UpdateDeck(ctx context.Context, arg UpdateDeckParams) (Deck, error) {
	row := q.db.QueryRow(ctx, updateDeck,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Tags,
		arg.NewCardsDailyLimit,
		arg.ModuleIDSet,
		arg.ModuleID,
		arg.UserID,
	)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Tags,
		&i.NewCardsDailyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModuleID,
	)
	return i, err
}
