// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kanban_cards.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createKanbanCard = `-- name: CreateKanbanCard :one

INSERT INTO kanban_cards (user_id, title, description, status, priority, assignee, position, type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, title, description, status, priority, assignee, position, verification_note, created_at, updated_at, type
`

type CreateKanbanCardParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Status      string    `json:"status"`
	Priority    string    `json:"priority"`
	Assignee    *string   `json:"assignee"`
	Position    int32     `json:"position"`
	Type        string    `json:"type"`
}

// apps/api/queries/kanban_cards.sql
func (q *Queries) CreateKanbanCard(ctx context.Context, arg CreateKanbanCardParams) (KanbanCard, error) {
	row := q.db.QueryRow(ctx, createKanbanCard,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Assignee,
		arg.Position,
		arg.Type,
	)
	var i KanbanCard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Assignee,
		&i.Position,
		&i.VerificationNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
	)
	return i, err
}

const deleteKanbanCard = `-- name: DeleteKanbanCard :exec
DELETE FROM kanban_cards WHERE id = $1 AND user_id = $2
`

type DeleteKanbanCardParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteKanbanCard(ctx context.Context, arg DeleteKanbanCardParams) error {
	_, err := q.db.Exec(ctx, deleteKanbanCard, arg.ID, arg.UserID)
	return err
}

const getKanbanCardByID = `-- name: GetKanbanCardByID :one
SELECT id, user_id, title, description, status, priority, assignee, position, verification_note, created_at, updated_at, type FROM kanban_cards WHERE id = $1
`

func (q *Queries) GetKanbanCardByID(ctx context.Context, id uuid.UUID) (KanbanCard, error) {
	row := q.db.QueryRow(ctx, getKanbanCardByID, id)
	var i KanbanCard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Assignee,
		&i.Position,
		&i.VerificationNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
	)
	return i, err
}

const listKanbanCardsByUser = `-- name: ListKanbanCardsByUser :many
SELECT id, user_id, title, description, status, priority, assignee, position, verification_note, created_at, updated_at, type FROM kanban_cards
WHERE user_id = $1
ORDER BY CASE status
    WHEN 'backlog' THEN 0
    WHEN 'todo' THEN 1
    WHEN 'in_progress' THEN 2
    WHEN 'done' THEN 3
END, position ASC
`

func (q *Queries) ListKanbanCardsByUser(ctx context.Context, userID uuid.UUID) ([]KanbanCard, error) {
	rows, err := q.db.Query(ctx, listKanbanCardsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KanbanCard
	for rows.Next() {
		var i KanbanCard
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.Position,
			&i.VerificationNote,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKanbanCardsByUserAndStatus = `-- name: ListKanbanCardsByUserAndStatus :many
SELECT id, user_id, title, description, status, priority, assignee, position, verification_note, created_at, updated_at, type FROM kanban_cards
WHERE user_id = $1 AND status = $2
ORDER BY position ASC
`

type ListKanbanCardsByUserAndStatusParams struct {
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
}

func (q *Queries) ListKanbanCardsByUserAndStatus(ctx context.Context, arg ListKanbanCardsByUserAndStatusParams) ([]KanbanCard, error) {
	rows, err := q.db.Query(ctx, listKanbanCardsByUserAndStatus, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KanbanCard
	for rows.Next() {
		var i KanbanCard
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.Position,
			&i.VerificationNote,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxPositionForStatus = `-- name: MaxPositionForStatus :one
SELECT COALESCE(MAX(position), -1)::int AS max_position
FROM kanban_cards
WHERE user_id = $1 AND status = $2
`

type MaxPositionForStatusParams struct {
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
}

func (q *Queries) MaxPositionForStatus(ctx context.Context, arg MaxPositionForStatusParams) (int32, error) {
	row := q.db.QueryRow(ctx, maxPositionForStatus, arg.UserID, arg.Status)
	var max_position int32
	err := row.Scan(&max_position)
	return max_position, err
}

const nextTodoCardForUser = `-- name: NextTodoCardForUser :one
SELECT id, user_id, title, description, status, priority, assignee, position, verification_note, created_at, updated_at, type FROM kanban_cards
WHERE user_id = $1 AND status = 'todo'
ORDER BY position ASC
LIMIT 1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) NextTodoCardForUser(ctx context.Context, userID uuid.UUID) (KanbanCard, error) {
	row := q.db.QueryRow(ctx, nextTodoCardForUser, userID)
	var i KanbanCard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Assignee,
		&i.Position,
		&i.VerificationNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
	)
	return i, err
}

const updateKanbanCard = `-- name: UpdateKanbanCard :one
UPDATE kanban_cards
SET title = COALESCE($2, title),
    description = COALESCE($3, description),
    status = COALESCE($4, status),
    priority = COALESCE($5, priority),
    assignee = COALESCE($6, assignee),
    position = COALESCE($7, position),
    type = COALESCE($8, type),
    verification_note = COALESCE($9, verification_note),
    updated_at = NOW()
WHERE id = $1 AND user_id = $10
RETURNING id, user_id, title, description, status, priority, assignee, position, verification_note, created_at, updated_at, type
`

type UpdateKanbanCardParams struct {
	ID               uuid.UUID `json:"id"`
	Title            *string   `json:"title"`
	Description      *string   `json:"description"`
	Status           *string   `json:"status"`
	Priority         *string   `json:"priority"`
	Assignee         *string   `json:"assignee"`
	Position         *int32    `json:"position"`
	Type             *string   `json:"type"`
	VerificationNote *string   `json:"verification_note"`
	UserID           uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateKanbanCard(ctx context.Context, arg UpdateKanbanCardParams) (KanbanCard, error) {
	row := q.db.QueryRow(ctx, updateKanbanCard,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Assignee,
		arg.Position,
		arg.Type,
		arg.VerificationNote,
		arg.UserID,
	)
	var i KanbanCard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Assignee,
		&i.Position,
		&i.VerificationNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
	)
	return i, err
}
