// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: letters.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createLetter = `-- name: CreateLetter :one

INSERT INTO letters (user_id, title, artist, original_lyrics, translation, deck_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, title, artist, original_lyrics, translation, deck_id, created_at, updated_at
`

type CreateLetterParams struct {
	UserID         uuid.UUID  `json:"user_id"`
	Title          string     `json:"title"`
	Artist         string     `json:"artist"`
	OriginalLyrics string     `json:"original_lyrics"`
	Translation    string     `json:"translation"`
	DeckID         *uuid.UUID `json:"deck_id"`
}

// apps/api/queries/letters.sql
func (q *Queries) CreateLetter(ctx context.Context, arg CreateLetterParams) (Letter, error) {
	row := q.db.QueryRow(ctx, createLetter,
		arg.UserID,
		arg.Title,
		arg.Artist,
		arg.OriginalLyrics,
		arg.Translation,
		arg.DeckID,
	)
	var i Letter
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Artist,
		&i.OriginalLyrics,
		&i.Translation,
		&i.DeckID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLetter = `-- name: DeleteLetter :exec
DELETE FROM letters WHERE id = $1 AND user_id = $2
`

type DeleteLetterParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteLetter(ctx context.Context, arg DeleteLetterParams) error {
	_, err := q.db.Exec(ctx, deleteLetter, arg.ID, arg.UserID)
	return err
}

const getLetterByID = `-- name: GetLetterByID :one
SELECT id, user_id, title, artist, original_lyrics, translation, deck_id, created_at, updated_at FROM letters WHERE id = $1
`

func (q *Queries) GetLetterByID(ctx context.Context, id uuid.UUID) (Letter, error) {
	row := q.db.QueryRow(ctx, getLetterByID, id)
	var i Letter
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Artist,
		&i.OriginalLyrics,
		&i.Translation,
		&i.DeckID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLettersByUser = `-- name: ListLettersByUser :many
SELECT id, user_id, title, artist, original_lyrics, translation, deck_id, created_at, updated_at FROM letters WHERE user_id = $1 ORDER BY updated_at DESC
`

func (q *Queries) ListLettersByUser(ctx context.Context, userID uuid.UUID) ([]Letter, error) {
	rows, err := q.db.Query(ctx, listLettersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Letter
	for rows.Next() {
		var i Letter
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Artist,
			&i.OriginalLyrics,
			&i.Translation,
			&i.DeckID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLetter = `-- name: UpdateLetter :one
UPDATE letters
SET title = COALESCE($2, title),
    artist = COALESCE($3, artist),
    original_lyrics = COALESCE($4, original_lyrics),
    translation = COALESCE($5, translation),
    deck_id = CASE
        WHEN $6::boolean THEN $7
        ELSE deck_id
    END,
    updated_at = NOW()
WHERE id = $1 AND user_id = $8
RETURNING id, user_id, title, artist, original_lyrics, translation, deck_id, created_at, updated_at
`

type UpdateLetterParams struct {
	ID             uuid.UUID  `json:"id"`
	Title          *string    `json:"title"`
	Artist         *string    `json:"artist"`
	OriginalLyrics *string    `json:"original_lyrics"`
	Translation    *string    `json:"translation"`
	DeckIDSet      *bool      `json:"deck_id_set"`
	DeckID         *uuid.UUID `json:"deck_id"`
	UserID         uuid.UUID  `json:"user_id"`
}

func (q *Queries) UpdateLetter(ctx context.Context, arg UpdateLetterParams) (Letter, error) {
	row := q.db.QueryRow(ctx, updateLetter,
		arg.ID,
		arg.Title,
		arg.Artist,
		arg.OriginalLyrics,
		arg.Translation,
		arg.DeckIDSet,
		arg.DeckID,
		arg.UserID,
	)
	var i Letter
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Artist,
		&i.OriginalLyrics,
		&i.Translation,
		&i.DeckID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
