// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countCardsReferencingMediaURL = `-- name: CountCardsReferencingMediaURL :one
SELECT count(*)
FROM cards
WHERE imagem_url = $1
`

func (q *Queries) CountCardsReferencingMediaURL(ctx context.Context, imagemUrl *string) (int64, error) {
	row := q.db.QueryRow(ctx, countCardsReferencingMediaURL, imagemUrl)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (
    id, user_id, kind, storage_path, original_filename, content_type, size_bytes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, kind, storage_path, original_filename, content_type, size_bytes, created_at
`

type CreateMediaParams struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	Kind             string    `json:"kind"`
	StoragePath      string    `json:"storage_path"`
	OriginalFilename *string   `json:"original_filename"`
	ContentType      string    `json:"content_type"`
	SizeBytes        int64     `json:"size_bytes"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.StoragePath,
		arg.OriginalFilename,
		arg.ContentType,
		arg.SizeBytes,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.StoragePath,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM media
WHERE id = $1 AND user_id = $2
`

type DeleteMediaParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteMedia(ctx context.Context, arg DeleteMediaParams) error {
	_, err := q.db.Exec(ctx, deleteMedia, arg.ID, arg.UserID)
	return err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, user_id, kind, storage_path, original_filename, content_type, size_bytes, created_at
FROM media
WHERE id = $1
`

func (q *Queries) GetMediaByID(ctx context.Context, id uuid.UUID) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaByID, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.StoragePath,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}
