// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Card struct {
	ID           uuid.UUID  `json:"id"`
	DeckID       uuid.UUID  `json:"deck_id"`
	Front        string     `json:"front"`
	Back         string     `json:"back"`
	AudioUrl     *string    `json:"audio_url"`
	ImagemUrl    *string    `json:"imagem_url"`
	Fonetica     *string    `json:"fonetica"`
	TtsEnabled   bool       `json:"tts_enabled"`
	Stability    float64    `json:"stability"`
	Difficulty   float64    `json:"difficulty"`
	Due          time.Time  `json:"due"`
	LastReview   *time.Time `json:"last_review"`
	State        string     `json:"state"`
	Reps         int32      `json:"reps"`
	Lapses       int32      `json:"lapses"`
	FsrsCardJson *string    `json:"fsrs_card_json"`
	RowVersion   int32      `json:"row_version"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

type Deck struct {
	ID                 uuid.UUID  `json:"id"`
	UserID             uuid.UUID  `json:"user_id"`
	Name               string     `json:"name"`
	Description        *string    `json:"description"`
	Tags               []string   `json:"tags"`
	NewCardsDailyLimit int32      `json:"new_cards_daily_limit"`
	CreatedAt          time.Time  `json:"created_at"`
	UpdatedAt          time.Time  `json:"updated_at"`
	ModuleID           *uuid.UUID `json:"module_id"`
}

type KanbanCard struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	Title            string    `json:"title"`
	Description      string    `json:"description"`
	Status           string    `json:"status"`
	Priority         string    `json:"priority"`
	Assignee         *string   `json:"assignee"`
	Position         int32     `json:"position"`
	VerificationNote string    `json:"verification_note"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	Type             string    `json:"type"`
}

type Letter struct {
	ID             uuid.UUID  `json:"id"`
	UserID         uuid.UUID  `json:"user_id"`
	Title          string     `json:"title"`
	Artist         string     `json:"artist"`
	OriginalLyrics string     `json:"original_lyrics"`
	Translation    string     `json:"translation"`
	DeckID         *uuid.UUID `json:"deck_id"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

type Medium struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	Kind             string    `json:"kind"`
	StoragePath      string    `json:"storage_path"`
	OriginalFilename *string   `json:"original_filename"`
	ContentType      string    `json:"content_type"`
	SizeBytes        int64     `json:"size_bytes"`
	CreatedAt        time.Time `json:"created_at"`
}

type Module struct {
	ID                 uuid.UUID `json:"id"`
	UserID             uuid.UUID `json:"user_id"`
	Name               string    `json:"name"`
	Description        *string   `json:"description"`
	SortOrder          int32     `json:"sort_order"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	PromptModuleTypeID string    `json:"prompt_module_type_id"`
}

type Note struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type PasswordResetToken struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	TokenHash string     `json:"token_hash"`
	ExpiresAt time.Time  `json:"expires_at"`
	UsedAt    *time.Time `json:"used_at"`
	CreatedAt time.Time  `json:"created_at"`
}

type PromptTemplate struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type RefreshToken struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	TokenHash  string    `json:"token_hash"`
	ExpiresAt  time.Time `json:"expires_at"`
	CreatedAt  time.Time `json:"created_at"`
	LastUsedAt time.Time `json:"last_used_at"`
	DeviceInfo *string   `json:"device_info"`
}

type Review struct {
	ID               uuid.UUID `json:"id"`
	CardID           uuid.UUID `json:"card_id"`
	UserID           uuid.UUID `json:"user_id"`
	Rating           int32     `json:"rating"`
	State            string    `json:"state"`
	ScheduledDays    int32     `json:"scheduled_days"`
	ElapsedDays      int32     `json:"elapsed_days"`
	ReviewDatetime   time.Time `json:"review_datetime"`
	ReviewDurationMs *int32    `json:"review_duration_ms"`
	Stability        float64   `json:"stability"`
	Difficulty       float64   `json:"difficulty"`
	WasNew           bool      `json:"was_new"`
}

type StudyPlan struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	Title           string    `json:"title"`
	Level           string    `json:"level"`
	Goal            string    `json:"goal"`
	GoldenRule      string    `json:"golden_rule"`
	Flexibility     string    `json:"flexibility"`
	NoFixedDeadline bool      `json:"no_fixed_deadline"`
	Steps           []byte    `json:"steps"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	Progress        []byte    `json:"progress"`
}

type User struct {
	ID                 uuid.UUID  `json:"id"`
	Email              string     `json:"email"`
	Nickname           string     `json:"nickname"`
	Name               *string    `json:"name"`
	HashedPassword     *string    `json:"hashed_password"`
	IsEmailVerified    bool       `json:"is_email_verified"`
	Provider           *string    `json:"provider"`
	Providers          []string   `json:"providers"`
	FsrsParameters     []float64  `json:"fsrs_parameters"`
	DesiredRetention   float64    `json:"desired_retention"`
	OptimizationStatus *string    `json:"optimization_status"`
	LastOptimization   *time.Time `json:"last_optimization"`
	Timezone           *string    `json:"timezone"`
	CreatedAt          time.Time  `json:"created_at"`
	UpdatedAt          time.Time  `json:"updated_at"`
}
