// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: modules.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createModule = `-- name: CreateModule :one

INSERT INTO modules (user_id, name, description, sort_order, prompt_module_type_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, description, sort_order, created_at, updated_at, prompt_module_type_id
`

type CreateModuleParams struct {
	UserID             uuid.UUID `json:"user_id"`
	Name               string    `json:"name"`
	Description        *string   `json:"description"`
	SortOrder          int32     `json:"sort_order"`
	PromptModuleTypeID string    `json:"prompt_module_type_id"`
}

// apps/api/queries/modules.sql
func (q *Queries) CreateModule(ctx context.Context, arg CreateModuleParams) (Module, error) {
	row := q.db.QueryRow(ctx, createModule,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.SortOrder,
		arg.PromptModuleTypeID,
	)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PromptModuleTypeID,
	)
	return i, err
}

const deleteModule = `-- name: DeleteModule :exec
DELETE FROM modules WHERE id = $1 AND user_id = $2
`

type DeleteModuleParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteModule(ctx context.Context, arg DeleteModuleParams) error {
	_, err := q.db.Exec(ctx, deleteModule, arg.ID, arg.UserID)
	return err
}

const getModuleByID = `-- name: GetModuleByID :one
SELECT id, user_id, name, description, sort_order, created_at, updated_at, prompt_module_type_id FROM modules WHERE id = $1
`

func (q *Queries) GetModuleByID(ctx context.Context, id uuid.UUID) (Module, error) {
	row := q.db.QueryRow(ctx, getModuleByID, id)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PromptModuleTypeID,
	)
	return i, err
}

const listModulesByUser = `-- name: ListModulesByUser :many
SELECT id, user_id, name, description, sort_order, created_at, updated_at, prompt_module_type_id FROM modules
WHERE user_id = $1
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListModulesByUser(ctx context.Context, userID uuid.UUID) ([]Module, error) {
	rows, err := q.db.Query(ctx, listModulesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Module
	for rows.Next() {
		var i Module
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PromptModuleTypeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModule = `-- name: UpdateModule :one
UPDATE modules
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    sort_order = COALESCE($4, sort_order),
    prompt_module_type_id = COALESCE($5, prompt_module_type_id),
    updated_at = NOW()
WHERE id = $1 AND user_id = $6
RETURNING id, user_id, name, description, sort_order, created_at, updated_at, prompt_module_type_id
`

type UpdateModuleParams struct {
	ID                 uuid.UUID `json:"id"`
	Name               *string   `json:"name"`
	Description        *string   `json:"description"`
	SortOrder          *int32    `json:"sort_order"`
	PromptModuleTypeID *string   `json:"prompt_module_type_id"`
	UserID             uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateModule(ctx context.Context, arg UpdateModuleParams) (Module, error) {
	row := q.db.QueryRow(ctx, updateModule,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.SortOrder,
		arg.PromptModuleTypeID,
		arg.UserID,
	)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PromptModuleTypeID,
	)
	return i, err
}
