// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prompt_templates.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPromptTemplate = `-- name: CreatePromptTemplate :one

INSERT INTO prompt_templates (user_id, name, body)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, body, created_at, updated_at
`

type CreatePromptTemplateParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
	Body   string    `json:"body"`
}

// apps/api/queries/prompt_templates.sql
func (q *Queries) CreatePromptTemplate(ctx context.Context, arg CreatePromptTemplateParams) (PromptTemplate, error) {
	row := q.db.QueryRow(ctx, createPromptTemplate, arg.UserID, arg.Name, arg.Body)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePromptTemplate = `-- name: DeletePromptTemplate :exec
DELETE FROM prompt_templates WHERE id = $1 AND user_id = $2
`

type DeletePromptTemplateParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePromptTemplate(ctx context.Context, arg DeletePromptTemplateParams) error {
	_, err := q.db.Exec(ctx, deletePromptTemplate, arg.ID, arg.UserID)
	return err
}

const getPromptTemplateByID = `-- name: GetPromptTemplateByID :one
SELECT id, user_id, name, body, created_at, updated_at FROM prompt_templates WHERE id = $1
`

func (q *Queries) GetPromptTemplateByID(ctx context.Context, id uuid.UUID) (PromptTemplate, error) {
	row := q.db.QueryRow(ctx, getPromptTemplateByID, id)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPromptTemplatesByUser = `-- name: ListPromptTemplatesByUser :many
SELECT id, user_id, name, body, created_at, updated_at FROM prompt_templates
WHERE user_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListPromptTemplatesByUser(ctx context.Context, userID uuid.UUID) ([]PromptTemplate, error) {
	rows, err := q.db.Query(ctx, listPromptTemplatesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptTemplate
	for rows.Next() {
		var i PromptTemplate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePromptTemplate = `-- name: UpdatePromptTemplate :one
UPDATE prompt_templates
SET name = COALESCE($2, name),
    body = COALESCE($3, body),
    updated_at = NOW()
WHERE id = $1 AND user_id = $4
RETURNING id, user_id, name, body, created_at, updated_at
`

type UpdatePromptTemplateParams struct {
	ID     uuid.UUID `json:"id"`
	Name   *string   `json:"name"`
	Body   *string   `json:"body"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdatePromptTemplate(ctx context.Context, arg UpdatePromptTemplateParams) (PromptTemplate, error) {
	row := q.db.QueryRow(ctx, updatePromptTemplate,
		arg.ID,
		arg.Name,
		arg.Body,
		arg.UserID,
	)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
