// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	BrowseUserCards(ctx context.Context, arg BrowseUserCardsParams) ([]Card, error)
	// Atomic "claim": only succeeds if the user isn't already marked as
	// running, avoiding the race between checking and setting the status
	// across concurrent requests/replicas.
	ClaimOptimizationRun(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	CountCardsByDeck(ctx context.Context, deckID uuid.UUID) (int64, error)
	CountCardsReferencingMediaURL(ctx context.Context, imagemUrl *string) (int64, error)
	CountDueCardsByDeck(ctx context.Context, arg CountDueCardsByDeckParams) (int64, error)
	CountNewCardsStudiedToday(ctx context.Context, arg CountNewCardsStudiedTodayParams) (int64, error)
	CountUserCards(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUserCardsByState(ctx context.Context, userID uuid.UUID) ([]CountUserCardsByStateRow, error)
	CountUserCardsCreatedSince(ctx context.Context, arg CountUserCardsCreatedSinceParams) (int64, error)
	CountUserCardsDueBy(ctx context.Context, arg CountUserCardsDueByParams) (int64, error)
	CountUserCardsEditedSince(ctx context.Context, arg CountUserCardsEditedSinceParams) (int64, error)
	CountUserCardsInUntaggedDecks(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateCard(ctx context.Context, arg CreateCardParams) (Card, error)
	// apps/api/queries/decks.sql
	CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error)
	// apps/api/queries/kanban_cards.sql
	CreateKanbanCard(ctx context.Context, arg CreateKanbanCardParams) (KanbanCard, error)
	// apps/api/queries/letters.sql
	CreateLetter(ctx context.Context, arg CreateLetterParams) (Letter, error)
	CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error)
	// apps/api/queries/modules.sql
	CreateModule(ctx context.Context, arg CreateModuleParams) (Module, error)
	// apps/api/queries/notes.sql
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	// apps/api/queries/prompt_templates.sql
	CreatePromptTemplate(ctx context.Context, arg CreatePromptTemplateParams) (PromptTemplate, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	// apps/api/queries/study_plans.sql
	CreateStudyPlan(ctx context.Context, arg CreateStudyPlanParams) (StudyPlan, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeckStatsByUser(ctx context.Context, arg DeckStatsByUserParams) ([]DeckStatsByUserRow, error)
	DeleteAllRefreshTokensForUser(ctx context.Context, userID uuid.UUID) error
	DeleteCard(ctx context.Context, id uuid.UUID) error
	DeleteDeck(ctx context.Context, id uuid.UUID) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteKanbanCard(ctx context.Context, id uuid.UUID) error
	DeleteLetter(ctx context.Context, id uuid.UUID) error
	DeleteMedia(ctx context.Context, arg DeleteMediaParams) error
	DeleteModule(ctx context.Context, id uuid.UUID) error
	DeleteNote(ctx context.Context, id uuid.UUID) error
	DeletePromptTemplate(ctx context.Context, id uuid.UUID) error
	DeleteRefreshToken(ctx context.Context, tokenHash string) error
	DeleteStudyPlan(ctx context.Context, id uuid.UUID) error
	GetCardByID(ctx context.Context, id uuid.UUID) (Card, error)
	GetDeckByID(ctx context.Context, id uuid.UUID) (Deck, error)
	// Locks the deck row so a concurrent review submission can't read the same
	// new-cards-studied-today count before this transaction commits its update.
	GetDeckByIDForUpdate(ctx context.Context, id uuid.UUID) (Deck, error)
	GetKanbanCardByID(ctx context.Context, id uuid.UUID) (KanbanCard, error)
	GetLetterByID(ctx context.Context, id uuid.UUID) (Letter, error)
	GetMediaByID(ctx context.Context, id uuid.UUID) (Medium, error)
	GetModuleByID(ctx context.Context, id uuid.UUID) (Module, error)
	GetNoteByID(ctx context.Context, id uuid.UUID) (Note, error)
	GetPromptTemplateByID(ctx context.Context, id uuid.UUID) (PromptTemplate, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetStudyPlanByID(ctx context.Context, id uuid.UUID) (StudyPlan, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByNickname(ctx context.Context, nickname string) (User, error)
	ListCardsByDeck(ctx context.Context, deckID uuid.UUID) ([]Card, error)
	ListDecksByUser(ctx context.Context, userID uuid.UUID) ([]Deck, error)
	ListDueCardsByDeck(ctx context.Context, arg ListDueCardsByDeckParams) ([]Card, error)
	ListDueCardsByUser(ctx context.Context, arg ListDueCardsByUserParams) ([]Card, error)
	ListKanbanCardsByUser(ctx context.Context, userID uuid.UUID) ([]KanbanCard, error)
	ListKanbanCardsByUserAndStatus(ctx context.Context, arg ListKanbanCardsByUserAndStatusParams) ([]KanbanCard, error)
	ListLettersByUser(ctx context.Context, userID uuid.UUID) ([]Letter, error)
	ListModulesByUser(ctx context.Context, userID uuid.UUID) ([]Module, error)
	ListNotesByUser(ctx context.Context, userID uuid.UUID) ([]Note, error)
	ListPromptTemplatesByUser(ctx context.Context, userID uuid.UUID) ([]PromptTemplate, error)
	ListReviewsByUserForOptimizer(ctx context.Context, userID uuid.UUID) ([]ListReviewsByUserForOptimizerRow, error)
	ListStudyPlansByUser(ctx context.Context, userID uuid.UUID) ([]StudyPlan, error)
	MaxPositionForStatus(ctx context.Context, arg MaxPositionForStatusParams) (int32, error)
	MoveCard(ctx context.Context, arg MoveCardParams) (Card, error)
	NextTodoCardForUser(ctx context.Context, userID uuid.UUID) (KanbanCard, error)
	// Run once at startup: the in-memory "running" guard is lost on restart, so
	// any row still marked 'running' is orphaned from a crash mid-optimization.
	ResetStaleRunningOptimizations(ctx context.Context) error
	TouchRefreshToken(ctx context.Context, id uuid.UUID) error
	UpdateCard(ctx context.Context, arg UpdateCardParams) (Card, error)
	UpdateCardAfterReview(ctx context.Context, arg UpdateCardAfterReviewParams) (Card, error)
	UpdateDeck(ctx context.Context, arg UpdateDeckParams) (Deck, error)
	UpdateKanbanCard(ctx context.Context, arg UpdateKanbanCardParams) (KanbanCard, error)
	UpdateLetter(ctx context.Context, arg UpdateLetterParams) (Letter, error)
	UpdateModule(ctx context.Context, arg UpdateModuleParams) (Module, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error)
	UpdatePromptTemplate(ctx context.Context, arg UpdatePromptTemplateParams) (PromptTemplate, error)
	UpdateStudyPlan(ctx context.Context, arg UpdateStudyPlanParams) (StudyPlan, error)
	UpdateStudyPlanProgress(ctx context.Context, arg UpdateStudyPlanProgressParams) (StudyPlan, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserFSRS(ctx context.Context, arg UpdateUserFSRSParams) (User, error)
	UpdateUserFSRSAfterOptimization(ctx context.Context, arg UpdateUserFSRSAfterOptimizationParams) (User, error)
	UpdateUserOptimizationStatus(ctx context.Context, arg UpdateUserOptimizationStatusParams) (User, error)
}

var _ Querier = (*Queries)(nil)
