// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: study_plans.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createStudyPlan = `-- name: CreateStudyPlan :one

INSERT INTO study_plans (user_id, title, level, goal, golden_rule, flexibility, no_fixed_deadline, steps)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, title, level, goal, golden_rule, flexibility, no_fixed_deadline, steps, created_at, updated_at, progress
`

type CreateStudyPlanParams struct {
	UserID          uuid.UUID `json:"user_id"`
	Title           string    `json:"title"`
	Level           string    `json:"level"`
	Goal            string    `json:"goal"`
	GoldenRule      string    `json:"golden_rule"`
	Flexibility     string    `json:"flexibility"`
	NoFixedDeadline bool      `json:"no_fixed_deadline"`
	Steps           []byte    `json:"steps"`
}

// apps/api/queries/study_plans.sql
func (q *Queries) CreateStudyPlan(ctx context.Context, arg CreateStudyPlanParams) (StudyPlan, error) {
	row := q.db.QueryRow(ctx, createStudyPlan,
		arg.UserID,
		arg.Title,
		arg.Level,
		arg.Goal,
		arg.GoldenRule,
		arg.Flexibility,
		arg.NoFixedDeadline,
		arg.Steps,
	)
	var i StudyPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Level,
		&i.Goal,
		&i.GoldenRule,
		&i.Flexibility,
		&i.NoFixedDeadline,
		&i.Steps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Progress,
	)
	return i, err
}

const deleteStudyPlan = `-- name: DeleteStudyPlan :exec
DELETE FROM study_plans WHERE id = $1 AND user_id = $2
`

type DeleteStudyPlanParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteStudyPlan(ctx context.Context, arg DeleteStudyPlanParams) error {
	_, err := q.db.Exec(ctx, deleteStudyPlan, arg.ID, arg.UserID)
	return err
}

const getStudyPlanByID = `-- name: GetStudyPlanByID :one
SELECT id, user_id, title, level, goal, golden_rule, flexibility, no_fixed_deadline, steps, created_at, updated_at, progress FROM study_plans WHERE id = $1
`

func (q *Queries) GetStudyPlanByID(ctx context.Context, id uuid.UUID) (StudyPlan, error) {
	row := q.db.QueryRow(ctx, getStudyPlanByID, id)
	var i StudyPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Level,
		&i.Goal,
		&i.GoldenRule,
		&i.Flexibility,
		&i.NoFixedDeadline,
		&i.Steps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Progress,
	)
	return i, err
}

const listStudyPlansByUser = `-- name: ListStudyPlansByUser :many
SELECT id, user_id, title, level, goal, golden_rule, flexibility, no_fixed_deadline, steps, created_at, updated_at, progress FROM study_plans WHERE user_id = $1 ORDER BY updated_at DESC
`

func (q *Queries) ListStudyPlansByUser(ctx context.Context, userID uuid.UUID) ([]StudyPlan, error) {
	rows, err := q.db.Query(ctx, listStudyPlansByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudyPlan
	for rows.Next() {
		var i StudyPlan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Level,
			&i.Goal,
			&i.GoldenRule,
			&i.Flexibility,
			&i.NoFixedDeadline,
			&i.Steps,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Progress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudyPlan = `-- name: UpdateStudyPlan :one
UPDATE study_plans
SET title = COALESCE($2, title),
    level = COALESCE($3, level),
    goal = COALESCE($4, goal),
    golden_rule = COALESCE($5, golden_rule),
    flexibility = COALESCE($6, flexibility),
    no_fixed_deadline = COALESCE($7, no_fixed_deadline),
    steps = COALESCE($8, steps),
    updated_at = NOW()
WHERE id = $1 AND user_id = $9
RETURNING id, user_id, title, level, goal, golden_rule, flexibility, no_fixed_deadline, steps, created_at, updated_at, progress
`

type UpdateStudyPlanParams struct {
	ID              uuid.UUID `json:"id"`
	Title           *string   `json:"title"`
	Level           *string   `json:"level"`
	Goal            *string   `json:"goal"`
	GoldenRule      *string   `json:"golden_rule"`
	Flexibility     *string   `json:"flexibility"`
	NoFixedDeadline *bool     `json:"no_fixed_deadline"`
	Steps           []byte    `json:"steps"`
	UserID          uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateStudyPlan(ctx context.Context, arg UpdateStudyPlanParams) (StudyPlan, error) {
	row := q.db.QueryRow(ctx, updateStudyPlan,
		arg.ID,
		arg.Title,
		arg.Level,
		arg.Goal,
		arg.GoldenRule,
		arg.Flexibility,
		arg.NoFixedDeadline,
		arg.Steps,
		arg.UserID,
	)
	var i StudyPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Level,
		&i.Goal,
		&i.GoldenRule,
		&i.Flexibility,
		&i.NoFixedDeadline,
		&i.Steps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Progress,
	)
	return i, err
}

const updateStudyPlanProgress = `-- name: UpdateStudyPlanProgress :one
UPDATE study_plans
SET progress = $2,
    updated_at = NOW()
WHERE id = $1 AND user_id = $3
RETURNING id, user_id, title, level, goal, golden_rule, flexibility, no_fixed_deadline, steps, created_at, updated_at, progress
`

type UpdateStudyPlanProgressParams struct {
	ID       uuid.UUID `json:"id"`
	Progress []byte    `json:"progress"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateStudyPlanProgress(ctx context.Context, arg UpdateStudyPlanProgressParams) (StudyPlan, error) {
	row := q.db.QueryRow(ctx, updateStudyPlanProgress, arg.ID, arg.Progress, arg.UserID)
	var i StudyPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Level,
		&i.Goal,
		&i.GoldenRule,
		&i.Flexibility,
		&i.NoFixedDeadline,
		&i.Steps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Progress,
	)
	return i, err
}
