// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimOptimizationRun = `-- name: ClaimOptimizationRun :one
UPDATE users
SET optimization_status = 'running', updated_at = NOW()
WHERE id = $1 AND optimization_status IS DISTINCT FROM 'running'
RETURNING id
`

// Atomic "claim": only succeeds if the user isn't already marked as
// running, avoiding the race between checking and setting the status
// across concurrent requests/replicas.
func (q *Queries) ClaimOptimizationRun(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, claimOptimizationRun, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, nickname, name, hashed_password, fsrs_parameters, desired_retention)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, nickname, name, hashed_password, is_email_verified, provider, providers, fsrs_parameters, desired_retention, optimization_status, last_optimization, timezone, created_at, updated_at
`

type CreateUserParams struct {
	Email            string    `json:"email"`
	Nickname         string    `json:"nickname"`
	Name             *string   `json:"name"`
	HashedPassword   *string   `json:"hashed_password"`
	FsrsParameters   []float64 `json:"fsrs_parameters"`
	DesiredRetention float64   `json:"desired_retention"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Nickname,
		arg.Name,
		arg.HashedPassword,
		arg.FsrsParameters,
		arg.DesiredRetention,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nickname,
		&i.Name,
		&i.HashedPassword,
		&i.IsEmailVerified,
		&i.Provider,
		&i.Providers,
		&i.FsrsParameters,
		&i.DesiredRetention,
		&i.OptimizationStatus,
		&i.LastOptimization,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, nickname, name, hashed_password, is_email_verified, provider, providers, fsrs_parameters, desired_retention, optimization_status, last_optimization, timezone, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nickname,
		&i.Name,
		&i.HashedPassword,
		&i.IsEmailVerified,
		&i.Provider,
		&i.Providers,
		&i.FsrsParameters,
		&i.DesiredRetention,
		&i.OptimizationStatus,
		&i.LastOptimization,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, nickname, name, hashed_password, is_email_verified, provider, providers, fsrs_parameters, desired_retention, optimization_status, last_optimization, timezone, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nickname,
		&i.Name,
		&i.HashedPassword,
		&i.IsEmailVerified,
		&i.Provider,
		&i.Providers,
		&i.FsrsParameters,
		&i.DesiredRetention,
		&i.OptimizationStatus,
		&i.LastOptimization,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByNickname = `-- name: GetUserByNickname :one
SELECT id, email, nickname, name, hashed_password, is_email_verified, provider, providers, fsrs_parameters, desired_retention, optimization_status, last_optimization, timezone, created_at, updated_at FROM users WHERE nickname = $1
`

func (q *Queries) GetUserByNickname(ctx context.Context, nickname string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByNickname, nickname)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nickname,
		&i.Name,
		&i.HashedPassword,
		&i.IsEmailVerified,
		&i.Provider,
		&i.Providers,
		&i.FsrsParameters,
		&i.DesiredRetention,
		&i.OptimizationStatus,
		&i.LastOptimization,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetStaleRunningOptimizations = `-- name: ResetStaleRunningOptimizations :exec
UPDATE users
SET optimization_status = 'failed', updated_at = NOW()
WHERE optimization_status = 'running'
`

// Run once at startup: the in-memory "running" guard is lost on restart, so
// any row still marked 'running' is orphaned from a crash mid-optimization.
func (q *Queries) ResetStaleRunningOptimizations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetStaleRunningOptimizations)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = COALESCE($2, email),
    nickname = COALESCE($3, nickname),
    name = COALESCE($4, name),
    hashed_password = COALESCE($5, hashed_password),
    timezone = CASE
        WHEN $6::boolean THEN $7
        ELSE timezone
    END,
    is_email_verified = CASE
        WHEN $8::boolean THEN false
        ELSE is_email_verified
    END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, nickname, name, hashed_password, is_email_verified, provider, providers, fsrs_parameters, desired_retention, optimization_status, last_optimization, timezone, created_at, updated_at
`

type UpdateUserParams struct {
	ID                 uuid.UUID `json:"id"`
	Email              *string   `json:"email"`
	Nickname           *string   `json:"nickname"`
	Name               *string   `json:"name"`
	HashedPassword     *string   `json:"hashed_password"`
	TimezoneSet        *bool     `json:"timezone_set"`
	Timezone           *string   `json:"timezone"`
	ResetEmailVerified *bool     `json:"reset_email_verified"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Nickname,
		arg.Name,
		arg.HashedPassword,
		arg.TimezoneSet,
		arg.Timezone,
		arg.ResetEmailVerified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nickname,
		&i.Name,
		&i.HashedPassword,
		&i.IsEmailVerified,
		&i.Provider,
		&i.Providers,
		&i.FsrsParameters,
		&i.DesiredRetention,
		&i.OptimizationStatus,
		&i.LastOptimization,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserFSRS = `-- name: UpdateUserFSRS :one
UPDATE users
SET fsrs_parameters   = COALESCE($2, fsrs_parameters),
    desired_retention = COALESCE($3, desired_retention),
    updated_at        = NOW()
WHERE id = $1
RETURNING id, email, nickname, name, hashed_password, is_email_verified, provider, providers, fsrs_parameters, desired_retention, optimization_status, last_optimization, timezone, created_at, updated_at
`

type UpdateUserFSRSParams struct {
	ID               uuid.UUID `json:"id"`
	FsrsParameters   []float64 `json:"fsrs_parameters"`
	DesiredRetention *float64  `json:"desired_retention"`
}

func (q *Queries) UpdateUserFSRS(ctx context.Context, arg UpdateUserFSRSParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserFSRS, arg.ID, arg.FsrsParameters, arg.DesiredRetention)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nickname,
		&i.Name,
		&i.HashedPassword,
		&i.IsEmailVerified,
		&i.Provider,
		&i.Providers,
		&i.FsrsParameters,
		&i.DesiredRetention,
		&i.OptimizationStatus,
		&i.LastOptimization,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserFSRSAfterOptimization = `-- name: UpdateUserFSRSAfterOptimization :one
UPDATE users
SET fsrs_parameters = $2,
    desired_retention = $3,
    optimization_status = 'completed',
    last_optimization = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, nickname, name, hashed_password, is_email_verified, provider, providers, fsrs_parameters, desired_retention, optimization_status, last_optimization, timezone, created_at, updated_at
`

type UpdateUserFSRSAfterOptimizationParams struct {
	ID               uuid.UUID `json:"id"`
	FsrsParameters   []float64 `json:"fsrs_parameters"`
	DesiredRetention float64   `json:"desired_retention"`
}

func (q *Queries) UpdateUserFSRSAfterOptimization(ctx context.Context, arg UpdateUserFSRSAfterOptimizationParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserFSRSAfterOptimization, arg.ID, arg.FsrsParameters, arg.DesiredRetention)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nickname,
		&i.Name,
		&i.HashedPassword,
		&i.IsEmailVerified,
		&i.Provider,
		&i.Providers,
		&i.FsrsParameters,
		&i.DesiredRetention,
		&i.OptimizationStatus,
		&i.LastOptimization,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserOptimizationStatus = `-- name: UpdateUserOptimizationStatus :one
UPDATE users
SET optimization_status = $2,
    last_optimization = COALESCE($3, last_optimization),
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, nickname, name, hashed_password, is_email_verified, provider, providers, fsrs_parameters, desired_retention, optimization_status, last_optimization, timezone, created_at, updated_at
`

type UpdateUserOptimizationStatusParams struct {
	ID                 uuid.UUID  `json:"id"`
	OptimizationStatus *string    `json:"optimization_status"`
	LastOptimization   *time.Time `json:"last_optimization"`
}

func (q *Queries) UpdateUserOptimizationStatus(ctx context.Context, arg UpdateUserOptimizationStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserOptimizationStatus, arg.ID, arg.OptimizationStatus, arg.LastOptimization)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nickname,
		&i.Name,
		&i.HashedPassword,
		&i.IsEmailVerified,
		&i.Provider,
		&i.Providers,
		&i.FsrsParameters,
		&i.DesiredRetention,
		&i.OptimizationStatus,
		&i.LastOptimization,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET hashed_password = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID             uuid.UUID `json:"id"`
	HashedPassword *string   `json:"hashed_password"`
}

// Used by the password reset flow (auth package) to set a new hashed
// password without touching any other user field.
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.HashedPassword)
	return err
}
